### ISSUE TITLE
Panic on nil pointer for the getEnforceSpec if not specified

### ISSUE THREAD

**Issue by mpryc** [migtools/oadp-non-admin#125]
go run ./cmd/main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x15e0859]

Running nac controller with DPA that has no enfroced spec

```shell
goroutine 1 [running]:
main.getEnforcedSpec(0xc00019a248, {0xc00004c0f0, 0xd})
   cmd/main.go:208 +0x219
main.main()
cmd/main.go:116 +0x4fa
exit status 2
make: *** [Makefile:89: run] Error 1
```

**Comment by shubham-pampattiwar** [comment]
@mpryc please link the PR for this issue
