### ISSUE TITLE
panic during backup creation

### ISSUE THREAD

**Issue by akarol** [migtools/oadp-non-admin#135]
```shell
#oc logs non-admin-controller-676f49b5f8-hz7dj  -n openshift-adp
2024-12-18T10:58:09Z	INFO	setup	starting manager
2024-12-18T10:58:09Z	INFO	controller-runtime.metrics	Starting metrics server
2024-12-18T10:58:09Z	INFO	starting server	{"name": "health probe", "addr": "[::]:8081"}
2024-12-18T10:58:09Z	INFO	controller-runtime.metrics	Serving metrics server	{"bindAddress": ":8080", "secure": false}
2024-12-18T10:58:09Z	INFO	Starting EventSource	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "source": "kind source: *v1alpha1.NonAdminBackup"}
2024-12-18T10:58:09Z	INFO	Starting EventSource	{"controller": "nonadminrestore", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminRestore", "source": "kind source: *v1alpha1.NonAdminRestore"}
2024-12-18T10:58:09Z	INFO	Starting EventSource	{"controller": "nonadminrestore", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminRestore", "source": "kind source: *v1.Restore"}
2024-12-18T10:58:09Z	INFO	Starting Controller	{"controller": "nonadminrestore", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminRestore"}
2024-12-18T10:58:09Z	INFO	Starting EventSource	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "source": "kind source: *v1.Backup"}
2024-12-18T10:58:09Z	INFO	Starting EventSource	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "source": "kind source: *v1.Backup"}
2024-12-18T10:58:09Z	INFO	Starting Controller	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup"}
2024-12-18T10:58:09Z	INFO	Starting workers	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "worker count": 1}
2024-12-18T10:58:09Z	INFO	Starting workers	{"controller": "nonadminrestore", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminRestore", "worker count": 1}
2024-12-18T10:58:09Z	DEBUG	Accepted NAB Create event	{"NonAdminBackupPredicate": {"name":"nabackup","namespace":"oadp-test-namespace-1"}}
2024-12-18T10:58:09Z	DEBUG	Accepted NAB Create event	{"NonAdminBackupPredicate": {"name":"nonadminbackup-sample-1","namespace":"oadp-test-namespace-1"}}
2024-12-18T10:58:09Z	DEBUG	Accepted NAB Create event	{"NonAdminBackupPredicate": {"name":"example","namespace":"test1"}}
2024-12-18T10:58:09Z	DEBUG	NonAdminBackup Reconcile start	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"nabackup","namespace":"oadp-test-namespace-1"}, "namespace": "oadp-test-namespace-1", "name": "nabackup", "reconcileID": "656d6b41-f3b2-4784-909d-caf0cda80226"}
2024-12-18T10:58:09Z	DEBUG	Executing direct deletion path	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"nabackup","namespace":"oadp-test-namespace-1"}, "namespace": "oadp-test-namespace-1", "name": "nabackup", "reconcileID": "656d6b41-f3b2-4784-909d-caf0cda80226"}
2024-12-18T10:58:09Z	DEBUG	NonAdminBackup status unchanged during direct API deletion	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"nabackup","namespace":"oadp-test-namespace-1"}, "namespace": "oadp-test-namespace-1", "name": "nabackup", "reconcileID": "656d6b41-f3b2-4784-909d-caf0cda80226"}
2024-12-18T10:58:09Z	DEBUG	NonAdminBackup Reconcile exit	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"nabackup","namespace":"oadp-test-namespace-1"}, "namespace": "oadp-test-namespace-1", "name": "nabackup", "reconcileID": "656d6b41-f3b2-4784-909d-caf0cda80226"}
2024-12-18T10:58:09Z	DEBUG	NonAdminBackup Reconcile start	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"nonadminbackup-sample-1","namespace":"oadp-test-namespace-1"}, "namespace": "oadp-test-namespace-1", "name": "nonadminbackup-sample-1", "reconcileID": "03281d1f-5313-4b75-9f25-3162cd51b95f"}
2024-12-18T10:58:09Z	DEBUG	Executing direct deletion path	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"nonadminbackup-sample-1","namespace":"oadp-test-namespace-1"}, "namespace": "oadp-test-namespace-1", "name": "nonadminbackup-sample-1", "reconcileID": "03281d1f-5313-4b75-9f25-3162cd51b95f"}
2024-12-18T10:58:09Z	DEBUG	NonAdminBackup status unchanged during direct API deletion	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"nonadminbackup-sample-1","namespace":"oadp-test-namespace-1"}, "namespace": "oadp-test-namespace-1", "name": "nonadminbackup-sample-1", "reconcileID": "03281d1f-5313-4b75-9f25-3162cd51b95f"}
2024-12-18T10:58:09Z	DEBUG	NonAdminBackup Reconcile exit	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"nonadminbackup-sample-1","namespace":"oadp-test-namespace-1"}, "namespace": "oadp-test-namespace-1", "name": "nonadminbackup-sample-1", "reconcileID": "03281d1f-5313-4b75-9f25-3162cd51b95f"}
2024-12-18T10:58:09Z	DEBUG	NonAdminBackup Reconcile start	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"example","namespace":"test1"}, "namespace": "test1", "name": "example", "reconcileID": "6b55b1e4-7880-4bfb-99f4-2db33d01569f"}
2024-12-18T10:58:09Z	DEBUG	Executing nab creation/update path	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"example","namespace":"test1"}, "namespace": "test1", "name": "example", "reconcileID": "6b55b1e4-7880-4bfb-99f4-2db33d01569f"}
2024-12-18T10:58:09Z	DEBUG	NonAdminBackup Phase already initialized	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"example","namespace":"test1"}, "namespace": "test1", "name": "example", "reconcileID": "6b55b1e4-7880-4bfb-99f4-2db33d01569f", "currentPhase": "New"}
2024-12-18T10:58:09Z	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "nonadminbackup", "controllerGroup": "oadp.openshift.io", "controllerKind": "NonAdminBackup", "NonAdminBackup": {"name":"example","namespace":"test1"}, "namespace": "test1", "name": "example", "reconcileID": "6b55b1e4-7880-4bfb-99f4-2db33d01569f"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x166eb30]

goroutine 158 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:111 +0x1e5
panic({0x17f1e80?, 0x297d960?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/migtools/oadp-non-admin/internal/common/function.ValidateBackupSpec(0xc0005769a0, 0xc00034c680)
	/workspace/internal/common/function/function.go:83 +0x30
github.com/migtools/oadp-non-admin/internal/controller.(*NonAdminBackupReconciler).validateSpec(0xc00043ec60, {0x1cab988, 0xc0006a1170}, {{0x1cafe30?, 0xc0006a11a0?}, 0x1?}, 0xc0005769a0)
	/workspace/internal/controller/nonadminbackup_controller.go:479 +0x74
github.com/migtools/oadp-non-admin/internal/controller.(*NonAdminBackupReconciler).Reconcile(0xc00043ec60, {0x1cab988, 0xc0006a1170}, {{{0xc00058de47?, 0x5?}, {0xc00058de40?, 0xc00059fd10?}}})
	/workspace/internal/controller/nonadminbackup_controller.go:138 +0x691
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1cafe30?, {0x1cab988?, 0xc0006a1170?}, {{{0xc00058de47?, 0xb?}, {0xc00058de40?, 0x0?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:114 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001ed290, {0x1cab9c0, 0xc00028b0e0}, {0x1871a40, 0xc00038f7c0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:311 +0x3bc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001ed290, {0x1cab9c0, 0xc00028b0e0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:261 +0x1be
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:222 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 82
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:218 +0x486
 ```

**Comment by mpryc** [comment]
@akarol Thank you for reporting this issue. The I see the spec for the non-admin was empty.

Possibly we have problem with the function to validate the spec, however this could have been fixed by:
   https://github.com/migtools/oadp-non-admin/pull/120
   
Issue to be confirmed if it still persists.

**Comment by mpryc** [comment]
@mateusoliveira43 that's probably the thing - old CRDs - I've tried with latest one and could not create NAB with empty spec. Older CRDs allowed that.
